weights:
  weather: 0.25
  trail: 0.35
  proximity: 0.1
  terrain_fit: 0.25
  secondary: 0.05
locations:
- key: urmston
  region: NW England
  name: Mosses and Canals (Urmston)
  lat: 53.448
  lon: -2.354
  drive_min_typical:
  - 0
  - 0
  terrain: distance, flat, gravel
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 1.0
  - 5.0
  notes: 'Flat gravel/multi-use surfaces for aerobic volume and easy spins.

    Very tolerant to rain; minimal maintenance impact.

    Great backup when hills are stormy or ruined by mud.

    '
- key: malham
  region: Yorkshire Dales
  name: Malham & Gordale
  lat: 54.061
  lon: -2.154
  drive_min_typical:
  - 0
  - 0
  terrain: hills, limestone, some_tech
  drainage: rocky
  mud_sensitivity: low
  duration_range:
  - 2.0
  - 5.0
  notes: 'Limestone pavements, steps and walled lanes; big vistas.

    Excellent wet resilience on rock; grassy links can be slick.

    Great shoulder‑season venue when Peaks are boggy.

    '
- key: reeth
  region: Yorkshire Dales
  name: Swaledale (Reeth)
  lat: 54.385
  lon: -1.944
  drive_min_typical:
  - 0
  - 0
  terrain: hills, moor, some_tech
  drainage: mixed
  mud_sensitivity: med
  duration_range:
  - 2.0
  - 5.0
  notes: 'Moorland crossings, mining tracks, and stony lanes.

    Mixed drainage; some boggy saddles linger.

    Quality big‑day country with proper remote feel.

    '
- key: llandegla
  region: North Wales
  name: Llandegla Trail Centre
  lat: 53.067
  lon: -3.115
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, technical, distance
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 1.0
  - 3.0
  notes: 'Surfaced red and black loops hold up superbly in wet.

    Drains fast; a consistent fallback in bad spells.

    Ideal for short sharp sessions or skill practice.

    '
- key: afan
  region: South Wales
  name: Afan Forest Park
  lat: 51.663
  lon: -3.651
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, technical, hills
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 1.5
  - 5.0
  notes: 'Multiple surfaced trail loops with excellent drainage.

    Forested and all-weather; a classic South Wales venue.

    Suits endurance or repeated technical runs.

    '
- key: cannock
  region: Staffordshire
  name: Cannock Chase
  lat: 52.754
  lon: -2.018
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, distance, some_tech
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 1.5
  - 4.0
  notes: 'Fast-draining trail centre near the Midlands.

    Great for structured efforts; consistent conditions.

    Can be busy weekends but solid wet-weather choice.

    '
- key: peashill
  region: Surrey Hills
  name: Peaslake / Pitch & Holmbury
  lat: 51.2
  lon: -0.441
  drive_min_typical:
  - 0
  - 0
  terrain: technical, steep, hills
  drainage: rocky
  mud_sensitivity: low
  duration_range:
  - 2.0
  - 5.0
  notes: 'Loamy Surrey Hills singletrack; flow and tech combined.

    Drainage lines make it rideable even after rain.

    Excellent year-round riding with elevation variety.

    '
- key: dartmoor_princetown
  region: SW England
  name: Dartmoor — Princetown Loops
  lat: 50.543
  lon: -3.99
  drive_min_typical:
  - 0
  - 0
  terrain: hills, moor, distance
  drainage: mixed_long_mud
  mud_sensitivity: high
  duration_range:
  - 2.0
  - 5.0
  notes: 'Peat and granite uplands; exposed and weather sensitive.

    Rapidly changing conditions; dries slowly after long rain.

    Stunning in crisp winter highs or summer evenings.

    '
- key: exmoor_porlock
  region: SW England
  name: Exmoor — Porlock & Doone
  lat: 51.208
  lon: -3.598
  drive_min_typical:
  - 0
  - 0
  terrain: hills, some_tech
  drainage: mixed
  mud_sensitivity: med
  duration_range:
  - 2.0
  - 5.0
  notes: 'Coastal climbs, wooded descents, and classic Exmoor lanes.

    Mixed drainage but dries faster than Dartmoor.

    Rewarding in spring or early autumn windows.

    '
- key: thetford
  region: East Anglia
  name: Thetford Forest
  lat: 52.433
  lon: 0.718
  drive_min_typical:
  - 0
  - 0
  terrain: distance, flat, trail_centre
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 1.0
  - 4.0
  notes: 'Flat pine forest network of sandy gravel trails.

    Rides well all year; zero climbing but excellent distance base.

    Ideal for endurance or steady winter training.

    '
- key: laggan_wolftrax
  region: Scottish Highlands
  name: Laggan Wolftrax
  lat: 57.0
  lon: -4.276
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, technical, hills
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 1.5
  - 4.0
  notes: 'Granite-based surfaces; highly durable and weatherproof.

    Steep technical lines with strong drainage.

    Perfect summer or winter hard option.

    '
- key: torridon
  region: Scottish Highlands
  name: Torridon
  lat: 57.546
  lon: -5.516
  drive_min_typical:
  - 0
  - 0
  terrain: steep, technical, big_mountain
  drainage: rocky
  mud_sensitivity: low
  duration_range:
  - 3.0
  - 6.0
  notes: 'Epic big-mountain rock terrain; very remote.

    Never truly muddy; weather and wind define rideability.

    Bucket-list terrain for strong riders in good conditions.

    '
- key: hayfield
  region: NW England
  name: Dark Peak (Hayfield)
  lat: 53.378
  lon: -1.948
  drive_min_typical:
  - 0
  - 0
  terrain: hills, steep, technical
  drainage: rocky
  mud_sensitivity: med
  duration_range:
  - 1.0
  - 6.0
  notes: 'Rocky descents and exposed moor edge climbs.

    Stays wet in winter once saturated; wind exposure is a factor.

    Superb when dry/high pressure, tough but rewarding otherwise.

    '
- key: marple
  region: NW England
  name: Dark Peak (Marple)
  lat: 53.394
  lon: -2.062
  drive_min_typical:
  - 0
  - 0
  terrain: hills, technical
  drainage: mixed
  mud_sensitivity: high
  duration_range:
  - 1.0
  - 2.5
  notes: 'Punchy climbs and tech bits; great start to link a longer Hayfield loop.

    Turns muddy quickly after even modest rain; better in breezy dries.

    Best for short-to-medium blasts or as a connector hub.

    '
- key: ladybower
  region: NW England
  name: Dark Peak (Ladybower)
  lat: 53.382
  lon: -1.72
  drive_min_typical:
  - 0
  - 0
  terrain: hills, steep, technical
  drainage: mixed_long_mud
  mud_sensitivity: high
  duration_range:
  - 2.5
  - 5.0
  notes: 'Big climbs and legendary rocky descents; iconic scenery.

    Peaty catchments mean it turns muddy fast and dries slowly.

    Magical in settled spells; punishing in long wet runs.

    '
- key: winter_hill
  region: NW England
  name: West Pennine Moors (Winter Hill)
  lat: 53.622
  lon: -2.513
  drive_min_typical:
  - 0
  - 0
  terrain: hills, moor, some_tech
  drainage: mixed
  mud_sensitivity: low
  duration_range:
  - 1.0
  - 5.0
  notes: 'Moorland tracks with rocky interludes; big-sky and exposed.

    Peat holds water; can be soggy after storms.

    Great when breezy/drying or with hard winter frosts.

    '
- key: gisburn
  region: NW England
  name: Gisburn Forest (Trail Centre)
  lat: 54.001
  lon: -2.36
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, technical, distance
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 1.5
  - 4.0
  notes: 'Stone-armoured reds and features keep riding consistent when wet.

    Good year-round option; sheltered forest mitigates wind.

    Easy to dial intensity by lapping sections.

    '
- key: whinlatter
  region: NW England
  name: Whinlatter (Trail Centre)
  lat: 54.611
  lon: -3.208
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, technical
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 1.5
  - 3.5
  notes: 'Fast-draining surfaced trails with steady gradients.

    Forested, wind-sheltered; great wet-weather fallback.

    Compact loops suit time-boxed rides.

    '
- key: grizedale
  region: NW England
  name: Grizedale Forest
  lat: 54.337
  lon: -3.039
  drive_min_typical:
  - 0
  - 0
  terrain: hills, some_tech
  drainage: mixed
  mud_sensitivity: med
  duration_range:
  - 2.0
  - 4.0
  notes: 'Bridleway/forestry mash-up with rocky lanes and views.

    Mixed drainage; some lines hold water.

    Flexible medium-length riding near South Lakes.

    '
- key: windermere
  region: NW England
  name: South Lakes (Windermere)
  lat: 54.38
  lon: -2.907
  drive_min_typical:
  - 0
  - 0
  terrain: hills, some_tech
  drainage: mixed_long_mud
  mud_sensitivity: high
  duration_range:
  - 2.5
  - 5.0
  notes: 'Steep climbs and bridleway tech with classic Lakes rock.

    Can feature longer muddy stretches in wet spells.

    Rewarding during settled windows or crisp winter days.

    '
- key: keswick
  region: NW England
  name: North Lakes (Keswick)
  lat: 54.601
  lon: -3.136
  drive_min_typical:
  - 0
  - 0
  terrain: hills, steep, technical
  drainage: rocky
  mud_sensitivity: med
  duration_range:
  - 1.5
  - 3.0
  notes: 'Shorter but spicier Lakes loops; punchy, rocky, and exposed.

    Rock holds up well but wind/rain can be savage.

    Top choice for sharp, high-quality tech sessions.

    '
- key: glentress
  region: Scottish Borders
  name: 7Stanes — Glentress
  lat: 55.65
  lon: -3.146
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, technical, hills
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 2.0
  - 5.0
  notes: 'Premier Scottish trail centre; surfaced and consistent.

    Holds up in almost all weather; sheltered in forest.

    Balanced climbs and descents make it ideal for all riders.

    '
- key: innerleithen
  region: Scottish Borders
  name: 7Stanes — Innerleithen
  lat: 55.619
  lon: -3.065
  drive_min_typical:
  - 0
  - 0
  terrain: steep, technical, hills
  drainage: rocky
  mud_sensitivity: med
  duration_range:
  - 2.0
  - 5.0
  notes: 'Steeper, more DH-oriented natural feel; rocky, drains well.

    Great in dry spells; still workable under light rain.

    A demanding venue for experienced riders.

    '
- key: kirroughtree
  region: Scottish Borders
  name: 7Stanes — Kirroughtree
  lat: 54.954
  lon: -4.457
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, technical, distance
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 2.0
  - 5.0
  notes: 'Granite slabs and surfaced trails; very wet tolerant.

    Climbs flow smoothly; great option in winter.

    One of the most reliable year-round rides in Scotland.

    '
- key: dalbeattie
  region: Scottish Borders
  name: 7Stanes — Dalbeattie
  lat: 54.931
  lon: -3.822
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, technical
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 1.5
  - 4.0
  notes: 'Slab features and rock lines; rides the same wet or dry.

    Compact loops with consistent drainage.

    Excellent wet-weather technical training.

    '
- key: mabie
  region: Scottish Borders
  name: 7Stanes — Mabie
  lat: 55.025
  lon: -3.649
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, some_tech
  drainage: mixed
  mud_sensitivity: med
  duration_range:
  - 1.5
  - 4.0
  notes: 'Mixed surfaced and natural singletrack.

    Some sections can hold puddles after prolonged rain.

    Fun rolling terrain ideal for mixed groups.

    '
- key: ae
  region: Scottish Borders
  name: 7Stanes — Ae
  lat: 55.169
  lon: -3.39
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, technical, hills
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 1.5
  - 4.0
  notes: 'Fast-draining surfaced trails plus natural lines.

    Excellent in wet or dry; one of the most weather-proof options.

    Sustained climbs, flowing descents, and good facilities.

    '
- key: glentrool
  region: Scottish Borders
  name: 7Stanes — Glentrool
  lat: 55.104
  lon: -4.537
  drive_min_typical:
  - 0
  - 0
  terrain: trail_centre, distance
  drainage: trail_centre
  mud_sensitivity: low
  duration_range:
  - 1.5
  - 4.0
  notes: 'Waymarked loops on hard surfaces; very rain tolerant.

    Long steady gradients perfect for endurance miles.

    Great all-weather touring base.'
