weights:
  weather: 0.25
  trail: 0.35
  proximity: 0.10
  terrain_fit: 0.25
  secondary: 0.05

locations:
  - key: urmston
    region: "NW England"
    name: Mosses and Canals (Urmston)
    lat: 53.448
    lon: -2.354
    drive_min_typical: [0, 0]
    terrain: "distance, flat, gravel"
    drainage: "trail_centre"
    mud_sensitivity: "low"
    duration_range: [1.0, 5.0]
    notes: "Start from home; flat gravel; well draining."
  - key: hayfield
    region: "NW England"
    name: Dark Peak (Hayfield)
    lat: 53.378
    lon: -1.948
    drive_min_typical: [45, 60]
    terrain: "hills, steep, technical"
    drainage: "rocky"
    mud_sensitivity: "med"
    duration_range: [1.0, 6.0]
    notes: "Rocky, technical; stays wet in winter once it turns."
  - key: marple
    region: "NW England"
    name: Dark Peak (Marple)
    lat: 53.394
    lon: -2.062
    drive_min_typical: [30, 40]
    terrain: "hills, technical"
    drainage: "mixed"
    mud_sensitivity: "high"
    duration_range: [1.0, 2.5]
    notes: "Can be muddy with little rain; good start point to link Hayfield."
  - key: eyam
    region: "NW England"
    name: White Peak (Eyam)
    lat: 53.283
    lon: -1.680
    drive_min_typical: [60, 70]
    terrain: "hills, some_tech"
    drainage: "mixed"
    mud_sensitivity: "med"
    duration_range: [2.5, 4.0]
    notes: "Well-draining limestone sections with some muddier bits."
  - key: llandegla
    region: "North Wales"
    name: North Wales (Llandegla)
    lat: 53.067
    lon: -3.115
    drive_min_typical: [60, 75]
    terrain: "trail_centre, technical, distance"
    drainage: "trail_centre"
    mud_sensitivity: "low"
    duration_range: [1.0, 3.0]
    notes: "Maintained trail centre; consistent surfaces when wet."
  - key: clwydian
    region: "North Wales"
    name: Clwydian Range
    lat: 53.162
    lon: -3.269
    drive_min_typical: [65, 75]
    terrain: "hills, some_tech"
    drainage: "mixed"
    mud_sensitivity: "med"
    duration_range: [2.5, 5.0]
    notes: "Good climbs and fun descents; mixed rock/mud."
  - key: windermere
    region: "NW England"
    name: South Lakes (Windermere)
    lat: 54.380
    lon: -2.907
    drive_min_typical: [70, 90]
    terrain: "hills, some_tech"
    drainage: "mixed_long_mud"
    mud_sensitivity: "high"
    duration_range: [2.5, 5.0]
    notes: "Steep climbing; some extended muddy sections."
  - key: keswick
    region: "NW England"
    name: North Lakes (Keswick)
    lat: 54.601
    lon: -3.136
    drive_min_typical: [80, 90]
    terrain: "hills, steep, technical"
    drainage: "rocky"
    mud_sensitivity: "med"
    duration_range: [1.5, 3.0]
    notes: "Steep, rocky tech; usually better for shorter/moderate rides."
  - key: malham
    region: "Yorkshire Dales"
    name: Malham & Gordale
    lat: 54.061
    lon: -2.154
    drive_min_typical: [90, 120]
    terrain: "hills, limestone, some_tech"
    drainage: "rocky"
    mud_sensitivity: "low"
    duration_range: [2.0, 5.0]
    notes: "Limestone pavements and bridleways; drains well, exposed."
  - key: sedbergh
    region: "Yorkshire Dales"
    name: Sedbergh & Howgills
    lat: 54.323
    lon: -2.527
    drive_min_typical: [90, 120]
    terrain: "hills, grassy, some_tech"
    drainage: "mixed_long_mud"
    mud_sensitivity: "high"
    duration_range: [2.0, 4.5]
    notes: "Grassy Howgill descents; slick when saturated."
  - key: glentress
    region: "Scottish Borders"
    name: 7Stanes — Glentress
    lat: 55.650
    lon: -3.146
    drive_min_typical: [210, 270]
    terrain: "trail_centre, technical, hills"
    drainage: "trail_centre"
    mud_sensitivity: "low"
    duration_range: [2.0, 5.0]
    notes: "Premier trail-centre surfaces; holds up in the wet."
  - key: torridon
    region: "Scottish Highlands"
    name: Torridon
    lat: 57.546
    lon: -5.516
    drive_min_typical: [500, 600]
    terrain: "steep, technical, big_mountain"
    drainage: "rocky"
    mud_sensitivity: "low"
    duration_range: [3.0, 6.0]
    notes: "Big-mountain rock; exposure limits, not mud."
