# MTB Ride Finder configuration (YAML) — diagnostic build
weights:
  weather: 0.25
  trail: 0.35
  proximity: 0.10
  terrain_fit: 0.25
  secondary: 0.05

locations:
  - key: urmston
    name: Mosses and Canals (Urmston)
    lat: 53.448
    lon: -2.354
    drive_min_typical: [0, 0]
    terrain: "distance, flat, gravel"
    drainage: "trail_centre"
    mud_sensitivity: "low"
    duration_range: [1.0, 5.0]
    notes: "Start from home; flat gravel; well draining."

  - key: hayfield
    name: Dark Peak (Hayfield)
    lat: 53.378
    lon: -1.948
    drive_min_typical: [45, 60]
    terrain: "hills, steep, technical"
    drainage: "rocky"
    mud_sensitivity: "med"
    duration_range: [1.0, 6.0]
    notes: "Rocky, technical; stays wet in winter once it turns."

  - key: marple
    name: Dark Peak (Marple)
    lat: 53.394
    lon: -2.062
    drive_min_typical: [30, 40]
    terrain: "hills, technical"
    drainage: "mixed"
    mud_sensitivity: "high"
    duration_range: [1.0, 2.5]
    notes: "Can be muddy with little rain; good start point to link Hayfield for big days."

  - key: eyam
    name: White Peak (Eyam)
    lat: 53.283
    lon: -1.680
    drive_min_typical: [60, 70]
    terrain: "hills, some_tech"
    drainage: "mixed"
    mud_sensitivity: "med"
    duration_range: [2.5, 4.0]
    notes: "Well-draining limestone sections with some muddier bits."
